version: 2.1

executors:
  openjdk8:
    docker:
      - image: cimg/openjdk:8.0

jobs:
  build:
    executor: openjdk8

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run:
          name: Build
          command: mvn -s .circleci/circleci-m2-settings.xml clean install

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  deploy:
    executor: openjdk8

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run:
          name: Deploy
          command: mvn -s .circleci/circleci-m2-settings.xml clean deploy -P cloudsoft-release -P sonatype-release

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          context:
            - org-global
            - cloudsoft-artifactory
          filters:
            branches:
              only: master

